{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "riot-im.serviceAccountName" . }}
  labels:
{{ include "riot-im.labels" . | indent 4 }}
{{- end -}}
